# Generated by Django 5.0.6 on 2024-05-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
